### ISSUE TITLE
Localized number when using together with QT

### ISSUE THREAD

**Issue by oldbridge** [IonMetadataWorkingGroup/API#7]
The floating point values are writen with a comma (,) on the xml file when integrating the API in QT. Locale is set to C in QT too.

Does the API in any way control that the xml are written overriding any locale?

**Comment by mbmathews** [comment]
As far as I know, the API does not set the locale for the C library.  It should use whatever was set prior to calling its methods.  From a standards perspective, the locale should be set to "C" when using the API.     I recommend checking the locale prior to calling the Save(...) function on the XmlProcessor logic.    Also might try forcing it using the following statement to see if that fixes it. 

std::setlocale(LC_ALL, "C");

Please let us know how this gets resolved.   We may need to add that statement into the Save/Load methods to enforce consistency.

Mike

**Comment by oldbridge** [comment]
Forcing the locale prior to saving doesn't fix the problem. I have to point out the API is compiled and used as a static library. Maybe it has to do with tinyxml?

**Comment by oldbridge** [comment]
Issue solved by adding std::setlocale(LC_NUMERIC,"C"); just after the creation of QT application.

**Comment by mbmathews** [comment]
Good to know.  I will close the issue.
